name: artifact-experiment
on:
  workflow_dispatch:

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: echo beepboop > testfile.txt
      - uses: actions/upload-artifact@v4
        with:
          name: testfile
          path: ./testfile.txt
  recall-artifact:
    needs: create-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: testfile
          path: ~/downloads
      - run: ls ~/downloads
      - run: unzip ~/downloads/testfile
      - run: ls ~/downloads
