name: create-dummy-release

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: echo beepboop > testfile.txt
      - uses: actions/upload-artifact@v4
        with:
          name: testfile
          path: ./testfile.txt
  create-github-release:
    if: github.event.pull_request.merged == true
    needs: create-artifact
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Get version property
        id: get-version-property
        run: |
          PACKAGE_VERSION=$(jq -r ".version" package.json)
          echo "package_version=$PACKAGE_VERSION" >> "$GITHUB_OUTPUT"
      - uses: actions/download-artifact@v4
        with:
          name: testfile
      - name: Create github release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get-version-property.outputs.package_version }}
          name: v${{ steps.get-version-property.outputs.package_version }}
          body: |
            asdfasdf
            asdfasdf
          token: ${{ secrets.GHA_PAT }}
          files: |
            package.json
            *.txt
          make_latest: true
