name: experiment-manual
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: what branch
        required: true


jobs:
  create-test-pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GHA_PAT }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          NEW_VERSION=$(jq -r ".version" package.json)
          PR_BODY="This PR was created automatically. I am testing stuff. \
          The current package.version is $NEW_VERSION.\n\
          I am trying hard to create multiline strings.\n\
          - list item 1\n\
          - list item 2"
          gh pr create -b dev -h main --title "Filler name" --body "$PR_BODY"