name: fired-flow
on:
  workflow_call:
    inputs:
      target-branch:
        description: what branch should be used
        required: false
        type: string
        default: ${{ github.ref_name }}

jobs:
  do-the-thing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target-branch }}
      - run: yarn logstr