name: publish-release
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag:
        description: tag to be published
        type: string
        required: true

jobs:
  pretend-to-release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "definitely did a release"
  create-main-to-dev-pr:
    needs: pretend-to-release
    env:
      GH_TOKEN: $github.token
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - run: gh pr create -B dev -H main --title "Filler name, change name manually" --body "Merging main into dev after release"




#  merge-main-to-dev:
#    needs: pretend-to-release
#    permissions:
#      contents: write
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - run: |
#          git fetch --all
#          git checkout main
#          git config --global user.name "botty-mc-botface"
#          git config --global user.email "botbotbot@imabot.bot"
#          git pull
#          git checkout dev
#          git pull
#          git pull origin main --rebase
#          git push --force
#
#