name: publish-release
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag:
        description: tag to be published
        type: string
        required: true

jobs:
  pretend-to-release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "definitely did a release"
  create-main-to-dev-pr:
    needs: pretend-to-release
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - run: |
          NEW_VERSION=$(jq -r ".version" package.json)
          git checkout -b m2d/v$NEW_VERSION
          git push --set-upstream origin m2d/v$NEW_VERSION
      - run: |
          NEW_VERSION=$(jq -r ".version" package.json)
          gh pr create -B dev -H m2d/v$NEW_VERSION --title "FILLER TITLE" --body "filler body"
          